bds_options:
  labeling:
    event_threshold: 0.4
    stochastic_iter: 1
    norm:
    scale:
  min_frames: 40
  birectional: False

trainer_options:
  accum_grad: 1
  grad_clip: 5.0
  log_interval: 250
  train_steps: 30000
  rampup_length: 7500
  consistency_cost: 2.0
  binarization_type: "global_threshold"
  threshold: 0.5
  early_stopping: False
  patience: 20