seed: "07"

wandb:
  project: 124-concat
  entity: team-417
  resume: True
  id:

data_root: /data2/syx/DCASE2021
#data_root: /data_ssd1/syx/sed_data/DCASE2021

resume:
pretrained:

sync_meta: metadata/train/synthetic.tsv
weak_meta: metadata/train/weak.tsv
unlabel_meta: metadata/train/unlabel_in_domain.tsv
valid_meta: metadata/validation/validation.tsv
valid_audio_dir: audio/validation/validation

max_len_seconds: 10

ngpu: 1

num_workers: 4

optimizer: "RAdam"
optimizer_params:
  lr: 0.001
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.000001

scheduler: "StepLR"
scheduler_params:
  step_size: 10000
  gamma: 0.1